/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hieus
 */
import javax.swing.table.DefaultTableModel;

public class fmDanhmucLoaiSP extends javax.swing.JFrame {

    /**
     * Creates new form fmDanhmucLoaiSP
     */
    DefaultTableModel tableModel;
    private String oldMaLoai = "";
    private String oldTenLoai = "";

    public fmDanhmucLoaiSP() {
        initComponents();
        // Khởi tạo table model với các cột
        tableModel = new DefaultTableModel(new String[]{"Mã loại", "Tên loại"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;  // Không cho phép chỉnh sửa trực tiếp các ô
            }
        };
        ShowData.setModel(tableModel);  // Gán model cho JTable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        ClearData = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        btthoat = new javax.swing.JButton();
        btkhongluu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ShowData = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH MỤC LOẠI SẢN PHẨM");

        jLabel2.setText("Mã loại: ");

        jLabel3.setText("Tên loại:");

        txtma.setText(" ");

        txtten.setText(" ");
        txtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenActionPerformed(evt);
            }
        });

        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        ClearData.setText("Xóa");
        ClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDataActionPerformed(evt);
            }
        });

        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        btthoat.setText("Thoát");
        btthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthoatActionPerformed(evt);
            }
        });

        btkhongluu.setText("K.Lưu");
        btkhongluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkhongluuActionPerformed(evt);
            }
        });

        ShowData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ShowData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btthem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ClearData, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btsua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btluu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btkhongluu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btsua)
                    .addComponent(ClearData)
                    .addComponent(btluu)
                    .addComponent(btthoat)
                    .addComponent(btkhongluu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDataActionPerformed
        // TODO add your handling code here:
        int n = tableModel.getRowCount() - 1;
        tableModel.removeRow(n);
    }//GEN-LAST:event_ClearDataActionPerformed

    private void btkhongluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkhongluuActionPerformed
        // TODO add your handling code here:
        txtma.setText(oldMaLoai);  // Đặt lại giá trị cũ cho mã loại
        txtten.setText(oldTenLoai); // Đặt lại giá trị cũ cho tên loại

        javax.swing.JOptionPane.showMessageDialog(null, "Đã khôi phục lại giá trị ban đầu!");

        // Không cho phép chỉnh sửa sau khi không lưu
        txtma.setEditable(false);
        txtten.setEditable(false);

    }//GEN-LAST:event_btkhongluuActionPerformed

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        // TODO add your handling code here:
        int selectedRow = ShowData.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem có dòng nào đang được chọn không
            // Lấy dữ liệu mới từ JTextField
            String maLoai = txtma.getText();
            String tenLoai = txtten.getText();

            // Cập nhật dữ liệu trong bảng
            ShowData.setValueAt(maLoai, selectedRow, 0);  // Cập nhật cột "Mã loại"
            ShowData.setValueAt(tenLoai, selectedRow, 1);  // Cập nhật cột "Tên loại"

            // Thông báo cập nhật thành công
            javax.swing.JOptionPane.showMessageDialog(null, "Cập nhật thành công!");

            // Không cho phép chỉnh sửa sau khi lưu
            txtma.setEditable(false);
            txtten.setEditable(false);
        } else {
            // Nếu không có dòng nào được chọn
            javax.swing.JOptionPane.showMessageDialog(null, "Không có dòng nào để lưu!");
        }
    }//GEN-LAST:event_btluuActionPerformed

    private void txttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        //Khởi tạo các components trên JFrame 
        String maLoai = txtma.getText().trim();
        String tenLoai = txtten.getText().trim();

        // Thêm dòng vào model nếu mã loại không rỗng
        if (!maLoai.isEmpty()) {
            tableModel.addRow(new Object[]{maLoai, tenLoai});
            txtma.setText(""); // Xóa trường nhập sau khi thêm
            txtten.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Mã loại không được để trống!");
        }


    }//GEN-LAST:event_btthemActionPerformed

    private void ShowDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowDataMouseClicked
        // TODO add your handling code here:
        try {
            int row = ShowData.getSelectedRow();  // Lấy dòng được chọn

            // Lấy giá trị từ dòng được chọn và hiển thị lên JTextField
            oldMaLoai = ShowData.getValueAt(row, 0).toString();  // Lưu giá trị cũ của mã loại
            oldTenLoai = ShowData.getValueAt(row, 1).toString();  // Lưu giá trị cũ của tên loại

            txtma.setText(oldMaLoai);
            txtten.setText(oldTenLoai);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ShowDataMouseClicked

    private void btthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btthoatActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        int selectedRow = ShowData.getSelectedRow();
        if (selectedRow != -1) {  // Kiểm tra xem người dùng đã chọn dòng nào chưa
            // Lưu giá trị cũ
            oldMaLoai = ShowData.getValueAt(selectedRow, 0).toString();
            oldTenLoai = ShowData.getValueAt(selectedRow, 1).toString();

            // Hiển thị giá trị cũ lên JTextField để chỉnh sửa
            txtma.setText(oldMaLoai);
            txtten.setText(oldTenLoai);

            // Cho phép chỉnh sửa mã loại và tên loại
            txtma.setEditable(true);
            txtten.setEditable(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để sửa!");
        }
    }//GEN-LAST:event_btsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmDanhmucLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmDanhmucLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmDanhmucLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmDanhmucLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmDanhmucLoaiSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearData;
    private javax.swing.JTable ShowData;
    private javax.swing.JButton btkhongluu;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btthoat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
